// import wrapper from "@/utils/redux/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OVER-ENGINEERING",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { store, props } = wrapper.useWrappedStore(null);
  return (
    <html lang="ko-kr">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
